require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe UserRolesController do

  def mock_user_role(stubs={})
    @mock_user_role ||= mock_model(UserRole, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all user_roles as @user_roles" do
      UserRole.stub(:all) { [mock_user_role] }
      get :index
      assigns(:user_roles).should eq([mock_user_role])
    end
  end

  describe "GET show" do
    it "assigns the requested user_role as @user_role" do
      UserRole.stub(:find).with("37") { mock_user_role }
      get :show, :id => "37"
      assigns(:user_role).should be(mock_user_role)
    end
  end

  describe "GET new" do
    it "assigns a new user_role as @user_role" do
      UserRole.stub(:new) { mock_user_role }
      get :new
      assigns(:user_role).should be(mock_user_role)
    end
  end

  describe "GET edit" do
    it "assigns the requested user_role as @user_role" do
      UserRole.stub(:find).with("37") { mock_user_role }
      get :edit, :id => "37"
      assigns(:user_role).should be(mock_user_role)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created user_role as @user_role" do
        UserRole.stub(:new).with({'these' => 'params'}) { mock_user_role(:save => true) }
        post :create, :user_role => {'these' => 'params'}
        assigns(:user_role).should be(mock_user_role)
      end

      it "redirects to the created user_role" do
        UserRole.stub(:new) { mock_user_role(:save => true) }
        post :create, :user_role => {}
        response.should redirect_to(user_role_url(mock_user_role))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved user_role as @user_role" do
        UserRole.stub(:new).with({'these' => 'params'}) { mock_user_role(:save => false) }
        post :create, :user_role => {'these' => 'params'}
        assigns(:user_role).should be(mock_user_role)
      end

      it "re-renders the 'new' template" do
        UserRole.stub(:new) { mock_user_role(:save => false) }
        post :create, :user_role => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested user_role" do
        UserRole.stub(:find).with("37") { mock_user_role }
        mock_user_role.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :user_role => {'these' => 'params'}
      end

      it "assigns the requested user_role as @user_role" do
        UserRole.stub(:find) { mock_user_role(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:user_role).should be(mock_user_role)
      end

      it "redirects to the user_role" do
        UserRole.stub(:find) { mock_user_role(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(user_role_url(mock_user_role))
      end
    end

    describe "with invalid params" do
      it "assigns the user_role as @user_role" do
        UserRole.stub(:find) { mock_user_role(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:user_role).should be(mock_user_role)
      end

      it "re-renders the 'edit' template" do
        UserRole.stub(:find) { mock_user_role(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested user_role" do
      UserRole.stub(:find).with("37") { mock_user_role }
      mock_user_role.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the user_roles list" do
      UserRole.stub(:find) { mock_user_role }
      delete :destroy, :id => "1"
      response.should redirect_to(user_roles_url)
    end
  end

end
